# Form implementation generated from reading ui file 'SRT_check_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(650, 30, 300, 340))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Save_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Save_btn.setGeometry(QtCore.QRect(860, 390, 75, 24))
        self.Save_btn.setObjectName("Save_btn")
        self.Cancel_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Cancel_btn.setGeometry(QtCore.QRect(650, 390, 75, 24))
        self.Cancel_btn.setObjectName("Cancel_btn")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 561, 340))
        self.widget.setObjectName("widget")
        self.OpenVideo_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.OpenVideo_btn.setGeometry(QtCore.QRect(40, 390, 75, 24))
        self.OpenVideo_btn.setObjectName("OpenVideo_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save_btn.setText(_translate("MainWindow", "儲存"))
        self.Cancel_btn.setText(_translate("MainWindow", "取消"))
        self.OpenVideo_btn.setText(_translate("MainWindow", "播放"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
